### ISSUE TITLE
Specify buffer name patterns

### ISSUE THREAD

**Issue by mark2185** [Aster89/vim-softwrap#7]
Currently it's triggered on `CursorHold` in `*`, but I'd like to be able to narrow it down only to specific buffers.

**Comment by Aster89** [comment]
Thinking about i though of this plugin for precisely one buffer, the stack trace of vimspecor. 

Anyway I'll give a look at your request after work.

**Comment by mark2185** [comment]
Well, I think I'll only ever use it for `vimspector.{Variables,StackTrace,Watches}` so I could just edit it manually, but if it's easily implemented as an option, I'm sure others will find some other uses as well.

 > Anyway I'll give a look at your request after work.

No rush, this is just a minor quality of life improvement, compared to the functionality the plugin itself offers :)

**Comment by Aster89** [comment]
@mark2185 , now you can `let g:softwrap_patterns = ['vimspector.{Variables,StackTrace,Watches}']` in your vimrc. If you suggest a better name for the option, I'll be happy to consider it. As regards it being a list, it's because of some change I'm gonna do next, with the addition of some doc.

**Comment by mark2185** [comment]
That works, thanks!

As for the name, maybe `softwrap_buffers_patterns` or something like that?
