### ISSUE TITLE
Should I (give an option to) show the popup only on demand?

### ISSUE THREAD

**Issue by Aster89** [Aster89/vim-softwrap#8]
Rather than, or in addition to, showing the popup on `CursorHold` and provide a mapping to dismiss it, I could allow not showing the popup on an event but provide a mapping to show it.

**Comment by mark2185** [comment]
If you export the function to show the soft wrap, people can do what they want with it, map it to a key, or even map it to an event.

**Comment by Aster89** [comment]
Hopefully closed with https://github.com/Aster89/vim-softwrap/commit/07df4111989cf2de833ba0640cebf58517860f95
