### ISSUE TITLE
Should I (give an option to) open the plugin on CursorMoved rather than CursorHold?

### ISSUE THREAD

**Issue by Aster89** [Aster89/vim-softwrap#9]
This would make it a real instantenous soft-wrap of current line. But could be a bit annoying to the eye. But probably worth providing as an option.

**Comment by mark2185** [comment]
If you solve #8 by exporting the function, this isn't needed as an option.

**Comment by Aster89** [comment]
Hopefully closed with https://github.com/Aster89/vim-softwrap/commit/07df4111989cf2de833ba0640cebf58517860f95
